### ISSUE TITLE
On default installation of nginx, the variable server_names_hash is commented which is giving this error

### ISSUE THREAD

**Issue by gagan0123** [rtCamp/easyengine#27]
nginx: [emerg] could not build the server_names_hash, you should increase server_names_hash_bucket_size: 32
nginx: configuration file /etc/nginx/nginx.conf test failed
[ Wed Jul 17 12:49:18 UTC 2013 ]  Unable To Reload Nginx

**Comment by brablc** [comment]
The article http://rtcamp.com/wordpress-nginx/tutorials/nginx/optimization/ is very nice on this topic.
I would just add some details to it:

- If you have `max_size` less than 10000 (https://github.com/nginx/nginx/blob/c3aed0a23392a509f64b740064f5f6633e8c89d8/src/core/ngx_hash.c#L289) and small `bucket_size`, you can expect long loading time because nginx would try to find optimal hash size in a loop. If you happen to have many collisions you would need bigger `max_size` to dilute them.

- If you have `max_size` bigger than 10000, there will be "only" 1000 loops performed before it would complain.

- `max_size` cannot be calculated from number of `server_names` or from combined length of server names. If you would have `bucket_size` 32, you would need maybe 10 or 100 bigger `max_size` than is your number of servers. If you would increase `bucket_size` to 512 and thus allow about 20 collisions in one bucket, you can keep `max_size` even less than number of your servers.
