### ISSUE TITLE
Download index.php instead of executing it

### ISSUE THREAD

**Issue by red010182** [rtCamp/easyengine#399]
when I visit mydomain.com, it just download the index.php file instead of executing it, similar as http://stackoverflow.com/questions/25591040/nginx-serves-php-files-as-downloads-instead-of-executing-them

please help

**Comment by gau1991** [comment]
Hi, @red010182 ,
It looks like you have created site type HTML instead of PHP.
You can use https://rtcamp.com/easyengine/docs/commands/site/update/ to update site type from HTML to PHP.
Or you can create new site using `ee site create example.com --php`

Now onwards for support use our community support forum http://community.rtcamp.com

**Comment by red010182** [comment]
Thanks for reply. Actually, I created it with
ee site create example.com --wp
And I found that it could be accessed from example.com/index.html, it seems the problem is html type. I'm trying to fix it.
