### ISSUE TITLE
support of procxy_cache

### ISSUE THREAD

**Issue by bml13** [rtCamp/easyengine#512]
When you will add support of Nginx proxy_cache (with pagespeed)

**Comment by cm896** [comment]
I am not familiar enough with proxy_cache to know it's benefits, or proposed usage.
How do you intend to use it, and how would it benefit?

I like the load balancing aspect, and using a proxy cache to decrease response times, but isn't this what fast cache is doing already with --wpfc?

https://www.digitalocean.com/community/tutorials/understanding-nginx-http-proxying-load-balancing-buffering-and-caching
https://kura.io/2010/02/14/more-nginx-proxy_cache-optimizations-and-nginx-load-balancing/
https://serversforhackers.com/nginx-caching/

**Comment by gau1991** [comment]
We are soon adding Nginx Proxy support with caching.
Its allready is our milestone: https://github.com/rtCamp/easyengine/issues/389

**Comment by rahul286** [comment]
@cm896 fastcgi_cache do it for single server, what proxy_cache is supposed to do for multiple server.

proxy_cache is recommended when using nginx as load-balancer or in front of some other web-server.

**Comment by bml13** [comment]
Yes, in my case I need to put proxy_cache in front of ngx_pagespeed

**Comment by rahul286** [comment]
@bml13 I think you are facing similar issue as discussed here - https://github.com/rtCamp/easyengine/issues/497

There are problems:

1. proxy_cache alone won't solve it. A lot of custom config needed to setup nginx downstream caching and so far no one manage to get it working right. So there is no working config yet. Pagespeed authors are refactoring pagespeed to play nice with proxy_cache.

2. proxy_cache or pagespeed downstream caching, in last week when tested added significant delays. Here is config we tested - https://gist.github.com/rahul286/22f5a0d8b3a6617bc240

That being said, if you have proxy_cache which is working with pagespeed downstream caching, please share your config so that we can test it and consider adding it to EE. :-)
