### ISSUE TITLE
Images not showing with most popular gallery plugin

### ISSUE THREAD

**Issue by daniel1943** [rtCamp/easyengine#588]
I am using Redis + hhvm

When I enable it to replace normal gallery I get this error for all images(none show): ERR_CONTENT_LENGTH_MISMATCH

2: Since mod_pagespeed doesn't work with redis what alternatives should be used for image compression ? As google pagespeed shows that 90% are unoptimized and gives low score :)

Cheers

**Comment by brennentsmith** [comment]
You could use a combination of the plugins: eww image optimizer (recompress) + imsanity (resize) to optimize the existing images and new images uploaded to the server. The advantage to this is that you don't have to deal with recompresssing all of the images again after clearing the pagespeed cache and they can do in place transformations so that the URLs match (aka. no URL modifications in PHP)

eww even supports webp conversions if you are up to adding the relevant nginx useragent configurations.

**Comment by harshadyeola** [comment]
@daniel1943 

I am closing this issue for now. Lets discuss this on community forum and if there is any update we will resume here.

can you please continue with this on community forum(http://community.rtcamp.com/c/easyengine)
