### ISSUE TITLE
Redis cache doesn´t work with hhvm

### ISSUE THREAD

**Issue by famfam** [rtCamp/easyengine#598]
Clean instalation Ubuntu 14.04 easyengine 3.3.3

Install site with redis Response Headers shows this

X-SRCache-Fetch-Status: HIT 
X-SRCache-Store-Status: BYPASS

Enable hhvm over same site Response Headers shows this

X-SRCache-Fetch-Status: MISS 
X-SRCache-Store-Status: BYPASS

Following this http://community.rtcamp.com/t/hhvm-and-wpredis/4845/6?u=danielote and adding this in redis-hhvm.conf

include fastcgi_params;
fastcgi_param  HTTP_ACCEPT_ENCODING      "";
fastcgi_pass hhvm;

Then Response Headers show this

X-SRCache-Fetch-Status: HIT
X-SRCache-Store-Status: BYPASS

**Comment by MattyLB** [comment]
Good catch, @famfam  -  if redis cache is working after the config change, are you seeing good results from having both features implemented?

**Comment by famfam** [comment]
No Matty, I disabled and purge hhvm because server (in production) crash frequently. It has more than 10.000 unique vistors at day.

**Comment by MattyLB** [comment]
Ok that's good to know and sorry to hear.  I have seen issues with HHVM locking up and not falling back to PHP after a certain HHVM cache fills up over time. Basically leaving the site down with little to no warning.

Without automated purging of this critical cache element when it reaches its threshold, I would honestly say that HHVM is not ready for most production environments. Hopefully there is a fix for this or a work-around because I have seen good performance when HHVM works.

I've also had better results with HHVM when it runs on a virtual instance with more than 1gig of RAM for a site with up to 1,000 daily visitors - so a site such as yours with over 10,000 unique visits each day might need significantly more RAM than even 2gig.  Might be something to look into.

**Comment by famfam** [comment]
The site is hosted on a server Linode 2Gb.

**Comment by xkidro** [comment]
I haven't made any tests but does anyone know if monit would solve this issue ? also why doesn't the fallback work ?

**Comment by maxsinus** [comment]
https://github.com/rtCamp/easyengine/commit/0962f9bd6087f0903ece2cabcc5bdc989f608088 didn't work for me. still, hhvm doesn't fallback.

And, the wp-admin goes white screen.
