### ISSUE TITLE
Uninstalled Pagespeed but "ee clean --all" still complains it can't clean pagespeed cache

### ISSUE THREAD

**Issue by shaneholloman** [rtCamp/easyengine#604]
```
root@ee:~# ee stack remove --pagespeed
Are you sure you to want to remove from server.
Package configuration will remain on server after this operation.
Any answer other than "yes" will be stop this operation :  yes
Successfully removed packages
root@ee:~# ee clean --all
Restart : memcached [OK]
Cleaning MemCache
Cleaning NGINX FastCGI cache
Cleaning opcache
Cleaning Redis cache
Unable to clean pagespeed cache
root@ee:~#
```

I attempted removed it because I don't use it

**Comment by iam404** [comment]
related to http://community.rtcamp.com/t/unable-to-clean-opcache/5068

**Comment by shaneholloman** [comment]
Still don't see the solution there - sorry if I am missing the obvious

**Comment by 2autunni** [comment]
Hi. 
the problem is in the file https://github.com/rtCamp/easyengine/blob/master/ee/cli/plugins/clean.py
The command ee clean --all try to clear all cache and assumes that all caching mechanisms are enabled.

As result if don't exists the directory '/var/ngx_pagespeed_cache' ee throws an error.

The workaround is to use only the flags for caching mechanisms actives

**Comment by shaneholloman** [comment]
@2autunni thank you for that explanation.... maybe it would be nice to have an option to make this a little prettier. Of course this is not really important in the grand scheme things if my error is not an indicator of a more serious issue. Cheers
